# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f1f68b900b7ae1889b7b7efa400714ac3b95ee7ea1ead2c76a4fca29e915df7910a0e5d08cc6298e2d12054312a9acaed22f3e12633f5feef7d8cc8465d2e3b

test:
  secret_key_base: ea99e25303d2e4bf5ca6bc54095f83cd02fefd47dea5c1cd0f503c70161744a7feb91ab7deb3f7686841bfe698947d930e3e86d96b300a8759822afb461facd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
